version: '3.8'

services:
  app:
    build: .
    container_name: openmrs-ai
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "python text2sql/OpenmrsTextToSqlForMysql.py"
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: openmrs-ai
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

# volumes:
#   db_data: