services:
  app:
    build:
      context: ./text2sql
      dockerfile: Dockerfile
    container_name: openmrs-ai
    ports:
      - "8000:8000"
    volumes:
      - ./text2sql:/app
    env_file:
      - ./text2sql/.env
    command: >
      sh -c "python text2sql/OpenmrsTextToSqlForMysql.py"